### ISSUE TITLE
The README.md file needs more info for new users

### ISSUE THREAD

**Issue by TomOndiba** [marabesi/twitter-clone-front-end#1]
I have added more notes for those who are new to Webpack just the way i was a few days ago. I had to go through the whole internet just to get my head around what is Webpack and how it works before even starting to test twitter-clone-front-end plugin.

Take a look at my fork at https://github.com/Twizanex/twitter-clone-front-end/blob/master/README.md

**Comment by marabesi** [comment]
Sorry for being late, why don't you send me a PR?

You've added a lot of good content I'd love merge it here.

**Comment by marabesi** [comment]
ping @TomOndiba

**Comment by TomOndiba** [comment]
@marabesi , Sorry for answering late. I have been on vacation. 18 days ago i was able to make an elgg plugin by using the template of your code. The plugin can be found here https://elgg.org/plugins/2665852
